server:
  port: 11101

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:11112/postgres
    username: postgres
    password: post123!
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

account:
  admin:
    id: admin
    password: admin

# mybatis:
#   type-aliases-package: com.madeg.logistics.domain
#   configuration.map-underscore-to-camel-case: true

security:
  jwt:
    token:
      key: madeGIsPopular1e34-willpro13ducealotprofits-2uvb9876aacx
      expire-length: 3600000
    access:
      expire:
        minute: 60
    refresh:
      expire:
        minute: 1440

logging:
  level:
    root: INFO
    sun.rmi.transport.tcp: OFF
    javax.management.remote.rmi: OFF

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: -1
  api-docs:
    path: /api
    show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**
